// Maps our internal alpha-3 codes to GeoJSON country names
export const CODE_TO_GEOJSON_NAME: Record<string, string> = {
  USA: 'United States of America',
  GBR: 'United Kingdom',
  CHN: 'China',
  RUS: 'Russia',
  UKR: 'Ukraine',
  DEU: 'Germany',
  FRA: 'France',
  JPN: 'Japan',
  KOR: 'South Korea',
  IND: 'India',
  BRA: 'Brazil',
  AUS: 'Australia',
  CAN: 'Canada',
  MEX: 'Mexico',
  ARG: 'Argentina',
  TUR: 'Turkey',
  ISR: 'Israel',
  IRN: 'Iran',
  SAU: 'Saudi Arabia',
  ITA: 'Italy',
  ESP: 'Spain',
  POL: 'Poland',
  NLD: 'Netherlands',
  SWE: 'Sweden',
  NOR: 'Norway',
  CHE: 'Switzerland',
  ZAF: 'South Africa',
  NGA: 'Nigeria',
  EGY: 'Egypt',
  KEN: 'Kenya',
  IDN: 'Indonesia',
  THA: 'Thailand',
  VNM: 'Vietnam',
  PHL: 'Philippines',
  MYS: 'Malaysia',
  SGP: 'Singapore',
  TWN: 'Taiwan',
  COL: 'Colombia',
  CHL: 'Chile',
  PER: 'Peru',
  VEN: 'Venezuela',
  NZL: 'New Zealand',
  IRQ: 'Iraq',
  SYR: 'Syria',
  LBN: 'Lebanon',
  PRK: 'North Korea',
  PAK: 'Pakistan',
  AFG: 'Afghanistan',
  MMR: 'Myanmar',
  ETH: 'Ethiopia',
  SDN: 'Sudan',
  UGA: 'Uganda',
  TZA: 'United Republic of Tanzania',
  PRT: 'Portugal',
  GRC: 'Greece',
  ROU: 'Romania',
  HUN: 'Hungary',
  CZE: 'Czech Republic',
  AUT: 'Austria',
  BEL: 'Belgium',
  DNK: 'Denmark',
  FIN: 'Finland',
  IRL: 'Ireland',
  ARE: 'United Arab Emirates',
  QAT: 'Qatar',
  CUB: 'Cuba',
  DOM: 'Dominican Republic',
  ECU: 'Ecuador',
  BOL: 'Bolivia',
  PRY: 'Paraguay',
  URY: 'Uruguay',
  PSE: 'West Bank',
}

// Reverse mapping: GeoJSON name -> our code
const _reverseMap: Record<string, string> = {}
for (const [code, name] of Object.entries(CODE_TO_GEOJSON_NAME)) {
  _reverseMap[name.toLowerCase()] = code
}

// Add common aliases
const ALIASES: Record<string, string> = {
  'united states': 'USA',
  'usa': 'USA',
  'uk': 'GBR',
  'britain': 'GBR',
  'england': 'GBR',
  'republic of korea': 'KOR',
  'korea': 'KOR',
  'democratic republic of the congo': 'COD',
  'republic of the congo': 'COG',
  'ivory coast': 'CIV',
  'cote d\'ivoire': 'CIV',
  'czech republic': 'CZE',
  'czechia': 'CZE',
  'burma': 'MMR',
  'palestine': 'PSE',
  'west bank': 'PSE',
}

export function geoNameToCode(geoName: string): string | null {
  const lower = geoName.toLowerCase()
  return _reverseMap[lower] || ALIASES[lower] || null
}
